// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Municipality.Data;

#nullable disable

namespace Municipality.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230617145453_AlterIrrigationTable48")]
    partial class AlterIrrigationTable48
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Municipality.Entities.AgriculturalLand", b =>
                {
                    b.Property<int>("LandQueueNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgricultureAreaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerPin")
                        .HasColumnType("TEXT");

                    b.HasKey("LandQueueNumber");

                    b.HasIndex("AgricultureAreaId");

                    b.ToTable("AgriculturalLands");
                });

            modelBuilder.Entity("Municipality.Entities.AgricultureArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VillageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VillageId");

                    b.ToTable("AgricultureAreas");
                });

            modelBuilder.Entity("Municipality.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("Municipality.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Municipality.Entities.Irrigation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgriculturalLandId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMessageSended")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("Irrigations");
                });

            modelBuilder.Entity("Municipality.Entities.IrrigationPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IrrigationId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ReceiptImage")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("SenderPin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IrrigationPayments");
                });

            modelBuilder.Entity("Municipality.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddresseePin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsViewed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Municipality.Entities.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Municipality.Entities.PastureModule.Pasture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Area")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentFreeArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VillageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VillageId");

                    b.ToTable("Pastures");
                });

            modelBuilder.Entity("Municipality.Entities.PastureModule.PasturePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Area")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PastureId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ReceiptImage")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("SenderPin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PastureId");

                    b.ToTable("PasturePayment");
                });

            modelBuilder.Entity("Municipality.Entities.PastureModule.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserPin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserPin");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Municipality.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Municipality.Entities.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CoastForAnHectare")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ContinuedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StoppedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VillageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VillageId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Municipality.Entities.User", b =>
                {
                    b.Property<string>("Pin")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AgriculturalLandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VillageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Pin");

                    b.HasIndex("VillageId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Municipality.Entities.Village", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistrictId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Villages");
                });

            modelBuilder.Entity("Municipality.Entities.AgriculturalLand", b =>
                {
                    b.HasOne("Municipality.Entities.AgricultureArea", null)
                        .WithMany("AgriculturalLands")
                        .HasForeignKey("AgricultureAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Municipality.Entities.AgricultureArea", b =>
                {
                    b.HasOne("Municipality.Entities.Village", null)
                        .WithMany("AgricultureAreas")
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Municipality.Entities.District", b =>
                {
                    b.HasOne("Municipality.Entities.Region", null)
                        .WithMany("Districts")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Municipality.Entities.Irrigation", b =>
                {
                    b.HasOne("Municipality.Entities.Round", null)
                        .WithMany("Irrigations")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Municipality.Entities.PastureModule.Pasture", b =>
                {
                    b.HasOne("Municipality.Entities.Village", null)
                        .WithMany("Pastures")
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Municipality.Entities.PastureModule.PasturePayment", b =>
                {
                    b.HasOne("Municipality.Entities.PastureModule.Pasture", null)
                        .WithMany("PasturePayments")
                        .HasForeignKey("PastureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Municipality.Entities.PastureModule.Pet", b =>
                {
                    b.HasOne("Municipality.Entities.User", null)
                        .WithMany("Pets")
                        .HasForeignKey("UserPin");
                });

            modelBuilder.Entity("Municipality.Entities.Round", b =>
                {
                    b.HasOne("Municipality.Entities.Village", null)
                        .WithMany("Rounds")
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Municipality.Entities.User", b =>
                {
                    b.HasOne("Municipality.Entities.Village", null)
                        .WithMany("Users")
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Municipality.Entities.Village", b =>
                {
                    b.HasOne("Municipality.Entities.District", null)
                        .WithMany("Villages")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Municipality.Entities.AgricultureArea", b =>
                {
                    b.Navigation("AgriculturalLands");
                });

            modelBuilder.Entity("Municipality.Entities.District", b =>
                {
                    b.Navigation("Villages");
                });

            modelBuilder.Entity("Municipality.Entities.PastureModule.Pasture", b =>
                {
                    b.Navigation("PasturePayments");
                });

            modelBuilder.Entity("Municipality.Entities.Region", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Municipality.Entities.Round", b =>
                {
                    b.Navigation("Irrigations");
                });

            modelBuilder.Entity("Municipality.Entities.User", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("Municipality.Entities.Village", b =>
                {
                    b.Navigation("AgricultureAreas");

                    b.Navigation("Pastures");

                    b.Navigation("Rounds");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
